# Site settings
title: MICHAL NEORAL
general_email: michalneoral@email.cz
academic_email: neoramic@fel.cvut.cz

description: > # this means to ignore newlines until "baseurl:"
  Michal Neoral - researcher in computer vision, focusing on motion estimation and visual tracking.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://michalneoral.github.io/" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: michalneoral
linkedin_username: michal-neoral-044542b2
#facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
